apiVersion: v1
items:
- apiVersion: image.openshift.io/v1
  kind: ImageStream
  metadata:
    annotations:
      openshift.io/generated-by: OpenShiftNewApp
    creationTimestamp: null
    labels:
      app: hello
      app.kubernetes.io/component: hello
      app.kubernetes.io/instance: hello
    name: hello
  spec:
    lookupPolicy:
      local: false
    tags:
    - annotations:
        openshift.io/imported-from: quay.io/redhattraining/hello-world-nginx
      from:
        kind: DockerImage
        name: quay.io/redhattraining/hello-world-nginx
      generation: null
      importPolicy: {}
      name: latest
      referencePolicy:
        type: ""
  status:
    dockerImageRepository: ""
- apiVersion: apps/v1
  kind: Deployment
  metadata:
    annotations:
      image.openshift.io/triggers: '[{"from":{"kind":"ImageStreamTag","name":"hello:latest"},"fieldPath":"spec.template.spec.containers[?(@.name==\"hello\")].image"}]'
      openshift.io/generated-by: OpenShiftNewApp
    creationTimestamp: null
    labels:
      app: hello
      app.kubernetes.io/component: hello
      app.kubernetes.io/instance: hello
    name: hello
  spec:
    replicas: 1
    selector:
      matchLabels:
        deployment: hello
    strategy: {}
    template:
      metadata:
        annotations:
          openshift.io/generated-by: OpenShiftNewApp
        creationTimestamp: null
        labels:
          deployment: hello
      spec:
        containers:
        - image: ' '
          name: hello
          ports:
          - containerPort: 8080
            protocol: TCP
          resources: {}
  status: {}
- apiVersion: v1
  kind: Service
  metadata:
    annotations:
      openshift.io/generated-by: OpenShiftNewApp
    creationTimestamp: null
    labels:
      app: hello
      app.kubernetes.io/component: hello
      app.kubernetes.io/instance: hello
    name: hello
  spec:
    ports:
    - name: 8080-tcp
      port: 8080
      protocol: TCP
      targetPort: 8080
    selector:
      deployment: hello
  status:
    loadBalancer: {}
kind: List
metadata: {}
